name: YouTube Bot Scheduler

on:
  schedule:
    - cron: '0 10-19 * * *'  
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-api-python-client

      - name: Run bot
        run: python bot.py
