name: YouTube Bot Scheduler

on:
  schedule:
    - cron: '0 0 * * *'   
    - cron: '24 2 * * *'    
    - cron: '48 4 * * *'    
    - cron: '12 7 * * *'    
    - cron: '36 9 * * *'    
    - cron: '0 12 * * *'    
    - cron: '24 14 * * *'   
    - cron: '48 16 * * *'   
    - cron: '12 19 * * *'   
    - cron: '36 21 * * *'   
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-api-python-client
          pip install pytz

      - name: Run bot
        run: python bot.py
